= argapp - a Python package for CLI application development
:toc: right
:toclevels: 3
:docinfo: shared
:nofooter:
:source-highlighter: pygments

== API

This chapter describes entities available to the developer. It has a specific structure:

* Each subchapter represents a scope: a module or a class.
The scope only has a description and an arbitrary number of sections.
* Each section represents either a variable or a function.
** The variable refers to variables, constants, fields, properties, etc.
It has a declaration, a description, and the following optional subsections:
*** *Defaults* - evaluation order if set to `None` or not set.
*** *Exceptions* - exceptions when the variable is set to some invalid value.
*** *Examples* - usage and error examples.
** The function refers to functions, methods, decorators, etc.
It has a declaration, a description, and the following optional subsections:
*** *Parameters* - a list of parameters accepted by the function.
*** *Returns* - a list of possible return values.
*** *Exceptions* - exceptions when invalid parameter values are provided.
*** *Examples* - usage and error examples.

'''

[#s-argapp]
=== `argapp`

The package is a module. It exports the following identifiers:

* <<f-argapp-main,`main()`>> - a function for parsing the command line and running the commands.
* <<c-argapp-arg,`Arg`>> - a class that represents a command line argument.
* <<c-argapp-app,`App`>> - a class that represents a command.
* <<c-argapp-arghelper,`ArgHelper`>> - a class for the argument description generation.
* <<c-argapp-apphelper,`AppHelper`>> - a class for the command description generation.
* <<c-argapp-completer,`Completer`>> - a base class for the completion generation.
* <<c-argapp-completernone,`CompleterNone`>> - a class for completion suppression.
* <<c-argapp-completerlist,`CompleterList`>> - a class for immediate list-based completion.
* <<c-argapp-completerpath,`CompleterPath`>> - a class for gradual path-based completion.
* <<c-argapp-callerror,`CallError`>> - an exception class to raise when there is an error during parsing or execution.

'''

[#f-argapp-main]
==== `+argapp.main(...)+`

[source,python]
----
def main(
    app: App,
    argv: list[str] = sys.argv,
) -> None:
    ...
----

Parses the command line and runs the commands.

===== Parameters

* `app` - The main command. If <<v-app-name,`app.name`>> is not set, `argv[0]` will be used as the command name.
* `argv` - The command line. In fact, it is treated as `Iterable[Any]` - each element is converted to `str`. Defaults to `sys.argv`.
Note that the first element is the command name (unused if <<v-app-name,`app.name`>> is set).

===== Returns

. Never returns, always calls `sys.exit()`.

===== Exceptions

. `SystemExit` with code 0 if nothing is raised.
. `SystemExit` with code 1 if an arbitrary error is raised.
The full stack trace is printed in this case.
. `SystemExit` with the corresponding code if <<c-argapp-callerror,`CallError`>> is raised.
The usage text and the error message are printed in this case.

'''

[#c-argapp-arg]
=== `argapp.Arg`

Represents a command line argument.

'''

[#v-arg-name]
==== `Arg.name`

[source,python]
----
class Arg:
    @property
    def name(self) -> str:
        ...

    @name.setter
    def name(self, v: str | None) -> None:
        ...
----

The name of the argument's value.

===== Defaults

. Uppercase <<v-arg-lopt,`self.lopt`>>, if set.
. Uppercase <<v-arg-sopt,`self.sopt`>>, if set.
. `""`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-arg-lopt]
==== `Arg.lopt`

[source,python]
----
class Arg:
    @property
    def lopt(self) -> str:
        ...

    @lopt.setter
    def lopt(self, v: str | None) -> None:
        ...
----

The long option name.

===== Defaults

. `""`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-arg-sopt]
==== `Arg.sopt`

[source,python]
----
class Arg:
    @property
    def sopt(self) -> str:
        ...

    @sopt.setter
    def sopt(self, v: str | None) -> None:
        ...
----

The short option name.

===== Defaults

. `""`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.
. `ValueError` if the value exceeds one character.

'''

[#v-arg-help]
==== `Arg.help`

[source,python]
----
class Arg:
    @property
    def help(self) -> str:
        ...

    @help.setter
    def help(self, v: str | None) -> None:
        ...
----

The argument's description.

===== Defaults

. `''`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-arg-helper]
==== `Arg.helper`

[source,python]
----
class Arg:
    @property
    def helper(self) -> ArgHelper:
        ...

    @helper.setter
    def helper(self, v: ArgHelper | None) -> None:
        ...
----

The argument's help text generator.

===== Defaults

. `<<c-argapp-arghelper,ArgHelper>>()`.

===== Exceptions

. `TypeError` if the type is not <<c-argapp-arghelper,`ArgHelper`>> or `None`.

'''

[#v-arg-type]
==== `Arg.type`

[source,python]
----
class Arg:
    @property
    def type(self) -> type:
        ...

    @type.setter
    def type(self, v: type | None) -> None:
        ...
----

The type of an individual value.

===== Defaults

. `bool` if <<v-arg-flag,`self.flag`>> is `True`.
. The type of the first item of <<v-arg-choices,`self.choices`>>, if it is not empty.
. The type of the first item of <<v-arg-default,`self.default`>>, if its type is `list` and it is not empty.
. The type of <<v-arg-default,`self.default`>>, if its type is not `list` and it is not `None`.
. `str`.

===== Exceptions

. `TypeError` if the type is not `type` or `None`.
. `ValueError` if the value is not `bool` and <<v-arg-flag,`self.flag`>> is `True`.
. `ValueError` if the value does not match <<v-arg-default,`self.default`>>.
. `ValueError` if the value does not match <<v-arg-choices,`self.choices`>>.

'''

[#v-arg-count]
==== `Arg.count`

[source,python]
----
class Arg:
    @property
    def count(self) -> int | str:
        ...

    @count.setter
    def count(self, v: int | str | None) -> None:
        ...
----

The number of values consumed by the argument:

. `0`: indicates a flag. Can be set if <<v-arg-optional,`self.optional`>> is `True`.
. `1`: a single value.
. `2` or greater: Multiple values, an exact number.
. `"?"`: a single value, zero or one.
. `"*"`: multiple values, zero or more.
. `"+"`: multiple values, one or more.
. `"~"`: multiple values, zero or more. Consume the rest of the command line without parsing. Can be set if <<v-arg-positional,`self.positional`>> is `True`.

===== Defaults

. `"*"` if the type of <<v-arg-default,`self.default`>> is `list`.
. `1`.

===== Exceptions

. `TypeError` if the type is not `int`, `str` or `None`.
. `ValueError` if the type is `int` and the value is negative.
. `ValueError` if the type is `str` and the value is not one of: `"?"`, `"*"`, `"+"`, `"~"`.
. `ValueError` if the value is `0` and <<v-arg-optional,`self.optional`>> is `False`.
. `ValueError` if the value is `"~"` and <<v-arg-positional,`self.positional`>> is `False`.
. `ValueError` if the value is `"+"` and <<v-arg-default,`self.default`>> is an empty `list`.
. `ValueError` if the type is `int` and the value does not match the number of items in <<v-arg-default,`self.default`>>.

'''

[#v-arg-default]
==== `Arg.default`

[source,python]
----
class Arg:
    @property
    def default(self) -> object | list | None:
        ...

    @default.setter
    def default(self, v: object | list | None) -> None:
        ...
----

The default value, applied if:

. <<v-arg-count,`self.count`>> is `'?'`, `'*'` or `'~'` and no values provided.
. <<v-arg-optional,`self.optional`>> is `True`, <<v-arg-suppress,`self.suppress`>> is `False`, and the argument is not mentioned.

===== Defaults

. `[]` if type of <<v-arg-count,`self.count`>> is `"*"` or `"~"`.
. `None`.

===== Exceptions

. `TypeError` if the type is not `list` and it is not <<v-arg-type,`self.type`>> or `None`.
. `TypeError` if the type is `list` and one of the items is not <<v-arg-type,`self.type`>>.
. `ValueError` if the type is not `list` and the value is not in <<v-arg-choices,`self.choices`>>.
. `ValueError` if the type is `list` and one of the items is not in <<v-arg-choices,`self.choices`>>.
. `ValueError` if the type is `list`, and the number of items does not match <<v-arg-count,`self.count`>>.
. `ValueError` if the value is an empty `list`, and <<v-arg-count,`self.count`>> is `"+"`.

'''

[#v-arg-choices]
==== `Arg.choices`

[source,python]
----
class Arg:
    @property
    def choices(self) -> dict:
        ...

    @choices.setter
    def choices(self, v: dict | None) -> None:
        ...
----

The set of possible values.

* Converted to dictionary from any `Iterable` despite the signature.
* The dictionary values are used as the descriptions, if provided.

===== Defaults

. `{}`.

===== Exceptions

. `TypeError` if the type is not `Iterable` or `None`.
. `TypeError` if the type of items is not <<v-arg-type,`self.type`>>.
. `ValueError` if the value does not contain <<v-arg-default,`self.default`>> if it is not `list`.
. `ValueError` if the value does not contain any item from <<v-arg-default,`self.default`>> if it is `list`.

'''

[#v-arg-restrict]
==== `Arg.restrict`

[source,python]
----
class Arg:
    @property
    def restrict(self) -> bool:
        ...

    @restrict.setter
    def restrict(self, v: bool | None) -> None:
        ...
----

Whether <<v-arg-choices,`self.choices`>> are restrictive.

===== Defaults

. `True`.

===== Exceptions

. `TypeError` if the type is not `bool` or `None`.

'''

[#v-arg-suppress]
==== `Arg.suppress`

[source,python]
----
class Arg:
    @property
    def suppress(self) -> bool:
        ...

    @suppress.setter
    def suppress(self, v: bool | None) -> None:
        ...
----

Whether to not set the optional argument to <<v-arg-default,`self.default`>> if it is not mentioned.

===== Defaults

. Always `False`, if <<v-arg-optional,`self.optional`>> is `False`.
. `False`.

===== Exceptions

. `TypeError` if the type is not `bool` or `None`.

'''

[#v-arg-required]
==== `Arg.required`

[source,python]
----
class Arg:
    @property
    def required(self) -> bool:
        ...

    @required.setter
    def required(self, v: bool | None) -> None:
        ...
----

Whether the optional argument must be mentioned.

===== Defaults

. Always `True`, if <<v-arg-optional,`self.optional`>> is `False`.
. `False`.

===== Exceptions

. `TypeError` if the type is not `bool` or `None`.

'''

[#v-arg-append]
==== `Arg.append`

[source,python]
----
class Arg:
    @property
    def append(self) -> bool:
        ...

    @append.setter
    def append(self, v: bool | None) -> None:
        ...
----

Whether the optional argument is appended on repeat.

===== Defaults

. Always `False`, if <<v-arg-optional,`self.optional`>> is `False`.
. `False`.

===== Exceptions

. `TypeError` if the type is not `bool` or `None`.

'''

[#v-arg-completer]
==== `Arg.completer`

[source,python]
----
class Arg:
    @property
    def completer(self) -> Completer:
        ...

    @completer.setter
    def completer(self, v: Completer | None) -> None:
        ...
----

The command line completer for the argument.

===== Defaults

. `<<c-argapp-completerlist,CompleterList>>(<<v-arg-choices,self.choices>>)`, if <<v-arg-choices,`self.choices`>> is not empty.
. `<<c-argapp-completerpath,CompleterPath>>()`, if <<v-arg-type,`self.type`>> is `str`.
. `<<c-argapp-completernone,CompleterNone>>()`.

===== Exceptions

. `TypeError` if the type is not <<c-argapp-completer,`Completer`>> or `None`.

'''

[#v-arg-optional]
==== `Arg.optional`

[source,python]
----
class Arg:
    @property
    def optional(self) -> bool:
        ...
----

Whether the argument is optional.

===== Defaults

. `True`, if <<v-arg-sopt,`self.sopt`>> or <<v-arg-lopt,`self.lopt`>> is set.
. `False`.

'''

[#v-arg-positional]
==== `Arg.positional`

[source,python]
----
class Arg:
    @property
    def positional(self) -> bool:
        ...
----

Whether the argument is positional.

===== Defaults

. `True`, if <<v-arg-sopt,`self.sopt`>> and <<v-arg-lopt,`self.lopt`>> are not set.
. `False`.

'''

[#v-arg-flag]
==== `Arg.flag`

[source,python]
----
class Arg:
    @property
    def flag(self) -> bool:
        ...
----

Whether the argument does not consume a value.

===== Defaults

. `True`, if <<v-arg-count,`self.count`>> is `0`.
. `False`.

'''

[#v-arg-single]
==== `Arg.single`

[source,python]
----
class Arg:
    @property
    def single(self) -> bool:
        ...
----

Whether the argument can consume at most one value.

===== Defaults

. `True`, if <<v-arg-count,`self.count`>> is `"?"` or `1`.
. `False`.

'''

[#v-arg-multiple]
==== `Arg.multiple`

[source,python]
----
class Arg:
    @property
    def multiple(self) -> bool:
        ...
----

Whether the argument can consume more than one value.

===== Defaults

. `True`, if <<v-arg-count,`self.count`>> is `"*"`, `"+"`, `"~"` or greater than one.
. `False`.

'''

[#f-arg---init--]
==== `+Arg.__init__(...)+`

[source,python]
----
class Arg:
    def __init__(
        self,
        name: str | None = None,
        lopt: str | None = None,
        sopt: str | None = None,
        help: str | None = None,
        helper: ArgHelper | None = None,
        type: type | None = None,
        count: int | str | None = None,
        default: object | list | None = None,
        choices: dict | None = None,
        restrict: bool | None = None,
        suppress: bool | None = None,
        required: bool | None = None,
        append: bool | None = None,
        completer: Completer | None = None,
    ) -> None:
        ...
----

The constructor. Sets each field in the declaration order.

===== Parameters

* `name` - corresponds to <<v-arg-name,`Arg.name`>>.
* `lopt` - corresponds to <<v-arg-lopt,`Arg.lopt`>>.
* `sopt` - corresponds to <<v-arg-sopt,`Arg.sopt`>>.
* `help` - corresponds to <<v-arg-help,`Arg.help`>>.
* `helper` - corresponds to <<v-arg-helper,`Arg.helper`>>.
* `type` - corresponds to <<v-arg-type,`Arg.type`>>.
* `count` - corresponds to <<v-arg-count,`Arg.count`>>.
* `default` - corresponds to <<v-arg-default,`Arg.default`>>.
* `choices` - corresponds to <<v-arg-choices,`Arg.choices`>>.
* `restrict` - corresponds to <<v-arg-restrict,`Arg.restrict`>>.
* `suppress` - corresponds to <<v-arg-suppress,`Arg.suppress`>>.
* `required` - corresponds to <<v-arg-required,`Arg.required`>>.
* `append` - corresponds to <<v-arg-append,`Arg.append`>>.
* `completer` - corresponds to <<v-arg-completer,`Arg.completer`>>.

'''

[#v-arg---call--bool]
==== `+Arg.__call__(bool)+`

[source,python]
----
class Arg:
    @overload
    def __call__(
        self,
        v: bool,
    ) -> bool:
        ...
----

Parse the command line value. This overload is called if:

* <<v-arg-flag,`self.flag`>> is `True`.
* <<v-arg-append,`self.append`>> is `False`.

===== Parameters

* `v` - `True` if the argrument is mentioned in the command line. `False` otherwise.

===== Returns

. <<v-arg-default,`self.default`>>, if v is `True`.
. `not <<v-arg-default,self.default>>`, if v is `False`.

'''

[#v-arg---call--int]
==== `+Arg.__call__(int)+`

[source,python]
----
class Arg:
    @overload
    def __call__(
        self,
        v: int,
    ) -> int:
        ...
----

Parse the command line value. This overload is called if:

* <<v-arg-flag,`self.flag`>> is `True`.
* <<v-arg-append,`self.append`>> is `True`.

===== Parameters

* `v` - a number of times the argument is mentioned in the command line.

===== Returns

. `v`.

'''

[#v-arg---call--str]
==== `+Arg.__call__(str)+`

[source,python]
----
class Arg:
    @overload
    def __call__(
        self,
        v: str | None,
    ) -> object | None:
        ...
----

Parse the command line value. This overload is called if:

* <<v-arg-single,`self.single`>> is `True`.
* <<v-arg-append,`self.append`>> is `False`.

===== Parameters

* `v` - a value from the command line. `None` if not provided.

===== Returns

. <<v-arg-default,`self.default`>>, if `v` is `None`.
. `<<v-arg-type,self.type>>(v)`.

===== Exceptions

. `CallError`, if <<v-arg-restrict,`self.restrict`>> is `True` and the value is not in <<v-arg-choices,`self.choices`>>.

[#v-arg---call--list]
==== `+Arg.__call__(list)+`

[source,python]
----
class Arg:
    @overload
    def __call__(
        self,
        v: list[str | None],
    ) -> list[object | None]:
        ...
----

Parse the command line value. This overload is called if:

* <<v-arg-single,`self.single`>> is `True`.
* <<v-arg-append,`self.append`>> is `True`.

===== Parameters

* `v` - a list of values from the command line associated with the argument.

===== Returns

. A `list` where each item `x` from `v` is set to:
.. <<v-arg-default,`self.default`>>, if `x` is `None`.
.. `<<v-arg-type,self.type>>(x)`.

===== Exceptions

. `CallError`, if <<v-arg-restrict,`self.restrict`>> is `True` and any item is not in <<v-arg-choices,`self.choices`>>.

'''

[#v-arg---call--list-str]
==== `+Arg.__call__(list[str])+`

[source,python]
----
class Arg:
    @overload
    def __call__(
        self,
        v: list[str] | None,
    ) -> list[object] | None:
        ...
----

Parse the command line value. This overload is called if:

* <<v-arg-multiple,`self.multiple`>> is `True`.
* <<v-arg-append,`self.append`>> is `False`.

===== Parameters

* `v` - a list of values from the command line.

===== Returns

. <<v-arg-default,`self.default`>>, if `v` is `None`.
. A `list` where each item `x` from `v` is set to `<<v-arg-type,self.type>>(x)`.

===== Exceptions

. `CallError`, if <<v-arg-restrict,`self.restrict`>> is `True` and any item is not in <<v-arg-choices,`self.choices`>>.

'''

[#v-arg---call--list-list]
==== `+Arg.__call__(list[list])+`

[source,python]
----
class Arg:
    @overload
    def __call__(
        self,
        v: list[list[str] | None],
    ) -> list[list[object] | None]:
        ...
----

Parse the command line value. This overload is called if:

* <<v-arg-multiple,`self.multiple`>> is `True`.
* <<v-arg-append,`self.append`>> is `True`.

===== Parameters

* `v` - a list of lists of values from the command line associated with the argument.

===== Returns

. A `list[list]` where each list `l` from `v` is converted to:
.. <<v-arg-default,`self.default`>>, if `l` is `None`.
.. A `list` where each item `x` from `l` is converted to `<<v-arg-type,self.type>>(x)`.

===== Exceptions

. `CallError`, if <<v-arg-restrict,`self.restrict`>> is `True` and any item is not in <<v-arg-choices,`self.choices`>>.

'''

[#c-argapp-app]
=== `argapp.App`

Represents a command.

'''

[#v-app-name]
==== `App.name`

[source,python]
----
class App:
    @property
    def name(self) -> str:
        ...

    @name.setter
    def name(self, v: str | None) -> None:
        ...
----

The command's name.

===== Defaults

. `""`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-app-help]
==== `App.help`

[source,python]
----
class App:
    @property
    def help(self) -> str:
        ...

    @help.setter
    def help(self, v: str | None) -> None:
        ...
----

The command's short description.

===== Defaults

. `''`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-app-prolog]
==== `App.prolog`

[source,python]
----
class App:
    @property
    def prolog(self) -> str:
        ...

    @prolog.setter
    def prolog(self, v: str | None) -> None:
        ...
----

The command's detailed description before arguments.

===== Defaults

. `''`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-app-epilog]
==== `App.epilog`

[source,python]
----
class App:
    @property
    def epilog(self) -> str:
        ...

    @epilog.setter
    def epilog(self, v: str | None) -> None:
        ...
----

The command's detailed description after arguments.

===== Defaults

. `''`.

===== Exceptions

. `TypeError` if the type is not `str` or `None`.

'''

[#v-app-helper]
==== `App.helper`

[source,python]
----
class App:
    @property
    def helper(self) -> AppHelper:
        ...

    @helper.setter
    def helper(self, v: AppHelper | None) -> None:
        ...
----

The command's help text generator.

===== Defaults

. `<<c-argapp-apphelper,AppHelper>>()`.

===== Exceptions

. `TypeError` if the type is not <<c-argapp-apphelper,`AppHelper`>> or `None`.

'''

[#c-argapp-arghelper]
=== `argapp.ArgHelper`

An argument description generation.

'''

[#c-argapp-apphelper]
=== `argapp.AppHelper`

A command description generation.

'''

[#c-argapp-completer]
=== `argapp.Completer`

A base class for completers.

'''

[#c-argapp-completernone]
=== `argapp.CompleterNone`

A <<c-argapp-completer, `Completer`>> for completion suppression.

'''

[#c-argapp-completerlist]
=== `argapp.CompleterList`

A <<c-argapp-completer, `Completer`>> for immediate list-based completion.

'''

[#c-argapp-completerpath]
=== `argapp.CompleterPath`

A <<c-argapp-completer, `Completer`>> for gradual path-based completion.

'''

[#c-argapp-callerror]
=== `argapp.CallError`

An exception to raise when there is an error during parsing or execution.

'''
