= argapp - a Python package for CLI application development
:toc: right
:toclevels: 3
:docinfo: shared
:nofooter:
:source-highlighter: pygments

== API

This chapter describes entities available to the developer. It has a specific structure:

* Each subchapter represents a scope: a module or a class.
The scope only has a description and an arbitrary number of sections.
* Each section represents either a variable or a function.
** The variable refers to variables, constants, fields, properties, etc.
It has a declaration, a description, and the following optional subsections:
*** *Defaults* - evaluation order if set to `None` or not set.
*** *Exceptions* - exceptions when the variable is set to some invalid value.
*** *Examples* - usage and error examples.
** The function refers to functions, methods, decorators, etc.
It has a declaration, a description, and the following optional subsections:
*** *Parameters* - a list of parameters accepted by the function.
*** *Returns* - a list of possible return values.
*** *Exceptions* - exceptions when invalid parameter values are provided.
*** *Examples* - usage and error examples.

'''

[#s-argapp]
=== `argapp`

The package is a module. It exports the following identifiers:

* <<f-argapp-main,`main()`>> - a function for parsing the command line and running the commands.
* <<c-argapp-arg,`Arg`>> - a class that represents a command line argument.
* <<c-argapp-app,`App`>> - a class that represents a command.
* <<c-argapp-arghelper,`ArgHelper`>> - a class for the argument description generation.
* <<c-argapp-apphelper,`AppHelper`>> - a class for the command description generation.
* <<c-argapp-completer,`Completer`>> - a base class for the completion generation.
* <<c-argapp-completernone,`CompleterNone`>> - a class for completion suppression.
* <<c-argapp-completerlist,`CompleterList`>> - a class for immediate list-based completion.
* <<c-argapp-completerpath,`CompleterPath`>> - a class for gradual path-based completion.
* <<c-argapp-callerror,`CallError`>> - an exception class to raise when there is an error during parsing or execution.

'''

[#f-argapp-main]
==== `+argapp.main(...)+`

[source,python]
----
def main(
    app: App,
    argv: list[str] = sys.argv,
) -> None:
    ...
----

Parses the command line and runs the commands.

===== Parameters

* `app` - The main command. If <<v-app-name,`app.name`>> is not set, `argv[0]` will be used as the command name.
* `argv` - The command line. In fact, it is treated as `Iterable[Any]` - each element is converted to `str`. Defaults to `sys.argv`.
Note that the first element is the command name (unused if <<v-app-name,`app.name`>> is set).

===== Returns

. Never returns, always calls `sys.exit()`.

===== Exceptions

. `SystemExit` with code 0 if nothing is raised.
. `SystemExit` with code 1 if an arbitrary error is raised.
The full stack trace is printed in this case.
. `SystemExit` with the corresponding code if <<c-argapp-callerror,`CallError`>> is raised.
The usage text and the error message are printed in this case.

'''

[#c-argapp-arg]
=== `argapp.Arg`

Represents a command line argument.

'''

[#c-argapp-app]
=== `argapp.App`

Represents a command.

'''

[#c-argapp-arghelper]
=== `argapp.ArgHelper`

An argument description generation.

'''

[#c-argapp-apphelper]
=== `argapp.AppHelper`

A command description generation.

'''

[#c-argapp-completer]
=== `argapp.Completer`

A base class for completers.

'''

[#c-argapp-completernone]
=== `argapp.CompleterNone`

A <<c-argapp-completer, `Completer`>> for completion suppression.

'''

[#c-argapp-completerlist]
=== `argapp.CompleterList`

A <<c-argapp-completer, `Completer`>> for immediate list-based completion.

'''

[#c-argapp-completerpath]
=== `argapp.CompleterPath`

A <<c-argapp-completer, `Completer`>> for gradual path-based completion.

'''

[#c-argapp-callerror]
=== `argapp.CallError`

An exception to raise when there is an error during parsing or execution.

'''
